language: c

compiler: gcc

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - g++-6

install:
  cd ci/travis && ./configure && make && make install

before_script:
  - cd -
  - pip install --user cpp-coveralls

script:
  - cd ci/coveralls/test
  - make
  - ./test_all.out
  - cd -

after_success:
  - coveralls --include ci/travis/src/ --gcov-options '\-lp'
